spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3307/blackjack
    username: root
    password: root
    properties:
      logger: DEBUG

  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/game_blackjack?authSource=admin