spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/blackjack
    username: root
    password: root
    properties:
      logger: DEBUG

  data:
    mongodb:
      uri: mongodb://localhost:27017/game_blackjack
