version: '3.8'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/
      ME_CONFIG_BASICAUTH: false

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: blackjack
      MYSQL_PASSWORD: root
    ports:
      - 3307:3306
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    image: adriavh/blackjack-app:latest
    build:
      context: .
    restart: on-failure
    depends_on:
      - mysql
      - mongo
    ports:
      - "8080:8080"
    environment:
      SPRING_R2DBC_URL: r2dbc:mysql://mysql:3306/blackjack
      SPRING_R2DBC_USERNAME: root
      SPRING_R2DBC_PASSWORD: root
      SPRING_DATA_MONGODB_URI: mongodb://root:root@mongo:27017/blackjack
