CREATE TABLE IF NOT EXISTS player (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  balance INT NOT NULL,
  games_won INT NOT NULL DEFAULT 0,
  games_played INT NOT NULL DEFAULT 0
);
